apiVersion: apps/v1
kind: Deployment
metadata:
  name: grow-mission-deployment
  labels:
    app: grow-mission
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grow-mission
  template:
    metadata:
      labels:
        app: grow-mission
    spec:
      containers:
      - name: grow-mission-container
        image: sswujmc/grow-mission:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: grow-mission-config
        - secretRef:
            name: grow-mission-secret
        volumeMounts:
        - name: gcp-key-volume
          mountPath: /app/config/gcp-key.json
          subPath: gcp-key.json
          readOnly: true
      volumes:
      - name: gcp-key-volume
        secret:
          secretName: grow-mission-secret
          items:
          - key: gcp-key.json
            path: gcp-key.json
---
apiVersion: v1
kind: Service
metadata:
  name: mission
spec:
  type: ClusterIP
  selector:
    app: grow-mission
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grow-mission-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grow-mission-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

